#!/usr/bin/env python3
"""Turn a raw generated render into a finished Retium post image.

    python3 tools/finish_image.py raw.png final.png \
        --headline "THE FEE IS A CONSTANT" --sub "$0.01 · KNOWN BEFORE YOU SUBMIT"

Steps:
  1. centre-crop to 16:9 (X timeline friendly)
  2. draw the headline + sub-line with a real font (image models garble text, so
     no text is ever generated by the model - it is added here, crisp every time)
  3. paste the official logo via tools/brand_logo.py

The render must be generated with an empty top-left area and an empty bottom band,
so the logo and the caption always land on clean background.
"""
import argparse
import os
import sys

from PIL import Image, ImageDraw, ImageFont

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from brand_logo import composite  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BOLD = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
REG = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"

INK = (237, 237, 237)          # near-white headline
BRAND = (252, 69, 10)          # #fc450a
MARGIN = 0.050                 # matches the logo left edge


def fit_font(draw, text, path, size, max_w):
    """Largest size <= `size` whose rendered width fits max_w."""
    while size > 12:
        f = ImageFont.truetype(path, size)
        if draw.textbbox((0, 0), text, font=f)[2] <= max_w:
            return f
        size -= 1
    return ImageFont.truetype(path, 12)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("src")
    ap.add_argument("dst")
    ap.add_argument("--headline", required=True)
    ap.add_argument("--sub", default="")
    ap.add_argument("--site", default="retium.org", help="URL footer, bottom right")
    ap.add_argument("--light", action="store_true", help="light render (dark logo ink)")
    a = ap.parse_args()

    im = Image.open(a.src).convert("RGB")
    W, H = im.size
    # centre-crop to 16:9
    target = 16 / 9
    if W / H > target:
        nw = round(H * target)
        im = im.crop(((W - nw) // 2, 0, (W - nw) // 2 + nw, H))
    else:
        nh = round(W / target)
        im = im.crop((0, (H - nh) // 2, W, (H - nh) // 2 + nh))
    W, H = im.size

    d = ImageDraw.Draw(im)
    x = round(MARGIN * W)
    max_w = round(0.92 * W) - x

    sub_f = fit_font(d, a.sub or " ", REG, round(0.038 * H), max_w) if a.sub else None
    head_f = fit_font(d, a.headline, BOLD, round(0.072 * H), max_w)

    sub_h = round(0.038 * H) if a.sub else 0
    gap = round(0.022 * H)
    head_h = head_f.size
    block = head_h + (gap + sub_h if a.sub else 0)
    y = round(0.945 * H) - block            # bottom-anchored inside the empty band

    # thin brand rule to the left of the text block
    rule_w = round(0.006 * W)
    d.rectangle([x, y + round(0.008 * H), x + rule_w, y + block], fill=BRAND)
    tx = x + rule_w + round(0.022 * W)

    d.text((tx, y), a.headline, font=head_f, fill=INK)
    if a.sub:
        d.text((tx, y + head_h + gap), a.sub, font=sub_f, fill=BRAND)

    # site URL, bottom right, on the same line as the last line of text
    if a.site:
        site_f = ImageFont.truetype(REG, round(0.034 * H))
        sw = d.textbbox((0, 0), a.site, font=site_f)[2]
        sy = y + (head_h + gap if a.sub else 0)
        sy += (sub_h - site_f.size) if a.sub else (head_h - site_f.size)
        d.text((round(0.95 * W) - sw, sy), a.site, font=site_f, fill=(155, 155, 163))

    im.save(a.dst)
    print(f"{os.path.basename(a.dst)}: {W}x{H}  \"{a.headline}\"")
    composite(a.dst, a.dst, light_bg=a.light)


if __name__ == "__main__":
    main()
